package com.secura.dnft.generic.bean;

public interface ErrorMessageCode {
	
	public final String ERR_MESSAGE_01="ERR_MESSAGE_01" ;
	public final String ERR_MESSAGE_02="ERR_MESSAGE_02" ;
	public final String ERR_MESSAGE_03="ERR_MESSAGE_03" ;
	public final String ERR_MESSAGE_04="ERR_MESSAGE_04" ;
	public final String ERR_MESSAGE_05="ERR_MESSAGE_05" ;
	public final String ERR_MESSAGE_06="ERR_MESSAGE_06" ;
	public final String ERR_MESSAGE_07="ERR_MESSAGE_07" ;
	public final String ERR_MESSAGE_08="ERR_MESSAGE_08" ;
	public final String ERR_MESSAGE_09="ERR_MESSAGE_09" ;
	public final String ERR_MESSAGE_10="ERR_MESSAGE_10" ;
	public final String ERR_MESSAGE_11="ERR_MESSAGE_11" ;
	public final String ERR_MESSAGE_12="ERR_MESSAGE_12" ;
	public final String ERR_MESSAGE_13="ERR_MESSAGE_13" ;
	public final String ERR_MESSAGE_14="ERR_MESSAGE_14" ;
	public final String ERR_MESSAGE_15="ERR_MESSAGE_15" ;
	public final String ERR_MESSAGE_16="ERR_MESSAGE_16" ;
	public final String ERR_MESSAGE_17="ERR_MESSAGE_17" ;
	public final String ERR_MESSAGE_18="ERR_MESSAGE_18" ;
	public final String ERR_MESSAGE_19="ERR_MESSAGE_19" ;
	public final String ERR_MESSAGE_20="ERR_MESSAGE_20" ;
	public final String ERR_MESSAGE_21="ERR_MESSAGE_21" ;
	public final String ERR_MESSAGE_22="ERR_MESSAGE_22" ;
	public final String ERR_MESSAGE_23="ERR_MESSAGE_23" ;
	public final String ERR_MESSAGE_24="ERR_MESSAGE_24" ;
	public final String ERR_MESSAGE_25="ERR_MESSAGE_25" ;
	public final String ERR_MESSAGE_26="ERR_MESSAGE_26" ;
	public final String ERR_MESSAGE_27="ERR_MESSAGE_27" ;
	public final String ERR_MESSAGE_28="ERR_MESSAGE_28" ;
	public final String ERR_MESSAGE_29="ERR_MESSAGE_29" ;
	public final String ERR_MESSAGE_30="ERR_MESSAGE_30" ;
	public final String ERR_MESSAGE_31="ERR_MESSAGE_31" ;
	public final String ERR_MESSAGE_32="ERR_MESSAGE_32" ;
	public final String ERR_MESSAGE_33="ERR_MESSAGE_33" ;
	public final String ERR_MESSAGE_34="ERR_MESSAGE_34" ;
	public final String ERR_MESSAGE_35="ERR_MESSAGE_35" ;
	public final String ERR_MESSAGE_36="ERR_MESSAGE_36" ;
	public final String ERR_MESSAGE_37="ERR_MESSAGE_37" ;
	public final String ERR_MESSAGE_38="ERR_MESSAGE_38" ;
	public final String ERR_MESSAGE_39="ERR_MESSAGE_39" ;
	public final String ERR_MESSAGE_40="ERR_MESSAGE_40" ;
	public final String ERR_MESSAGE_41="ERR_MESSAGE_41" ;
	public final String ERR_MESSAGE_42="ERR_MESSAGE_42" ;
	public final String ERR_MESSAGE_43="ERR_MESSAGE_43" ;
	public final String ERR_MESSAGE_44="ERR_MESSAGE_44" ;
	public final String ERR_MESSAGE_45="ERR_MESSAGE_45" ;
	public final String ERR_MESSAGE_46="ERR_MESSAGE_46" ;
	public final String ERR_MESSAGE_47="ERR_MESSAGE_47" ;
	public final String ERR_MESSAGE_48="ERR_MESSAGE_48" ;
}
