spring.application.name=secura.dnft

# Local development database (use application-railway.properties for production)

#spring.datasource.url=jdbc:postgresql://localhost:5432/secura_dnft
#spring.datasource.url=jdbc:postgresql://localhost:5432/dnft_new
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true



spring.jackson.time-zone=Asia/Kolkata

face.recognition.service.url=${FACE_RECOGNITION_SERVICE_URL:}


transaction.chunk=50
