spring.application.name=secura.dnft

spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway?sslmode=require&ssl=true
spring.datasource.username=postgres
spring.datasource.password=JsgJLowNdHVGeeuJNUvmWbvypWKnNCQh
server.port=${PORT:8080}
server.address=${SERVER_ADDRESS:0.0.0.0}
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

#razorPay.key=rzp_test_SRxceBfBqGmeGy;
#razorPay.secret=RO2SpqK1H96ShjlmkttpA2cX;


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

privacy.secrect.key=1234567890123456
privacy.secrect.algo=AES

#auth.crypto.key-base64=U2VjdXJhTG9naW5LZXlGb3JXZWJBcHBWMS0zMkJ5dGVLZXkhIQ==
#auth.crypto.iv-base64=U2VjdXJhSW5pdFZlY3RvcjEyMw==
#auth.crypto.transformation=AES/CBC/PKCS5Padding


auth.crypto.key-base64=U2VjdXJhTG9naW5LZXlBRVMyNTZWYWx1ZTEyMzQ1Njc=
auth.crypto.iv-base64=U2VjdXJhSW5pdFZlYzEyMw==
auth.crypto.transformation=AES/CBC/PKCS5Padding


#auth.crypto.key-base64=U2VjdXJhTG9naW5LZXlBRVMyNTZWYWx1ZTEyMzQ1Njc=
#auth.crypto.iv-base64=U2VjdXJhSW5pdFZlYzEyMw==
#auth.crypto.transformation=AES/CBC/PKCS5Padding