spring.application.name=secura.dnft

spring.datasource.url=${JDBC_DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:secura_dnft}}}
spring.datasource.username=${PGUSER:${SPRING_DATASOURCE_USERNAME:postgres}}
spring.datasource.password=${PGPASSWORD:${SPRING_DATASOURCE_PASSWORD:__MISSING_DB_PASSWORD__}}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
server.address=${SERVER_ADDRESS:0.0.0.0}

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

#razorPay.key=rzp_test_SRxceBfBqGmeGy;
#razorPay.secret=RO2SpqK1H96ShjlmkttpA2cX;


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

privacy.secrect.key=1234567890123456
privacy.secrect.algo=AES

auth.crypto.key-base64=U2VjdXJhTG9naW5LZXlBRVMyNTZWYWx1ZTEyMzQ1Njc=
auth.crypto.iv-base64=U2VjdXJhSW5pdFZlYzEyMw==
auth.crypto.transformation=AES/CBC/PKCS5Padding

spring.jackson.time-zone=UTC
spring.jackson.time-zone=Asia/Kolkata
#spring.jackson.serialization.write-dates-as-timestamps=false
#razorPay.key=rzp_test_SRxceBfBqGmeGy;
#razorPay.secret=RO2SpqK1H96ShjlmkttpA2cX;
